### PR TITLE
Add Service-Accounts directory to mock_ldap_directory

### PR DESCRIPTION
**Pull request by ampacker**
@jdavisp3 cc @lucaswiman Add Service-Accounts to directory in `mock_ldap_directory`

### CODE REVIEW

**Review by jdavisp3 — APPROVED** [review]
Nice, thanks for fixing @ampacker .

**Comment by ampacker** [comment]
thanks @jdavisp3! I'll bump version then merge

**Comment by ampacker** [comment]
eh, new GH UX needs approval of changes to merge (only change here https://github.com/counsyl/baya/pull/13/commits/80a8255915474c832bf634aa5f7c2e55bc71356f)

**Review by jdavisp3 — APPROVED** [review]

**Comment by ampacker** [comment]
oh, it's because I don't have write access. One of you want to go ahead and merge the PR?

**Comment by jdavisp3** [comment]
I don't seem to have it either 😄

**Pull request merged**
