### PR TITLE
Make compatible with django auth ldap 1.6.1

### PR DESCRIPTION
**Pull request by hrichards**
@lucaswiman 

Modernizes the function declaration of `initialize` to allow for `django-auth-ldap>=1.5.0`.

# What Changed

Between versions 1.2 and 1.6 (I think [in 1.5](https://django-auth-ldap.readthedocs.io/en/latest/changes.html#id3)), `django-auth-ldap` changed the call it makes to `python-ldap's` `initialize` function from this:

https://github.com/django-auth-ldap/django-auth-ldap/blob/7c4d0fe4dbbd8fa8bfd472cbc23906351d074e2b/django_auth_ldap/backend.py#L836

```
 self._connection = self.backend.ldap.initialize(uri)
```

to this:

https://github.com/django-auth-ldap/django-auth-ldap/blob/47b301dadd1ee09f3ebdbb2ee189de14843b3614/django_auth_ldap/backend.py#L862

```
 self._connection = self.backend.ldap.initialize(uri, bytes_mode=False)
```

Note the addition of `bytes_mode=False`.

Because the implementation of Baya's `NestedLDAPGroupsBackend` spoofs calls to [`python-ldap's` `initialize` function](http://www.python-ldap.org/en/python-ldap-3.0.0/reference/ldap.html#ldap.initialize) in the following code:

https://github.com/counsyl/baya/blob/f319cef5e95cd6a166265d51ae0ea236b6f65be3/baya/backend.py#L83-L85

that call signature must be updated to include the new kwarg `bytes_mode`.

The goal of `ReconnectingLDAP ` in the code snippet above is to replace calls to `initialize` with instantiations of `ReconnectLDAPObject` so that Baya will reconnect automatically if connections drop.  And since the function signatures of [`initialize`](http://www.python-ldap.org/en/python-ldap-3.0.0/reference/ldap.html#ldap.initialize) and [`ReconnectLDAPObject`](http://www.python-ldap.org/en/python-ldap-3.0.0/reference/ldap.html#ldap.ReconnectLDAPObject) are different, not least in that the latter doesn't recognize the kwarg `bytes_mode`, the kwarg must be in the function definition of our `initialize` but cannot be passed on to our initialization of `ReconnectLDAPObject`.

# How Tested

I'm deploying this to our internal systems as we speak.  If a manual LDAP test succeeds, then I think this PR is safe to merge.  Note that because a default is given, and the kwarg is not used in the function body, then this change is backwards-compatible.

### CODE REVIEW

**Comment by jdavisp3** [comment]
The build failures indicate we might need to remove some dependencies on some `pip` code that is no longer in new versions of `pip`.

**Comment by hrichards** [comment]
@jdavisp3 Hmm, yeah, looks like we're not supposed to be importing `pip` internals like `PipSession`: https://github.com/pypa/pip/issues/5272.

**Comment by jtratner** [comment]
https://github.com/hrichards/baya/pull/1 <-- I think this is better way to do the install_requires part.

**Comment by jtratner** [comment]
See https://github.com/counsyl/baya/pull/21 for potentially better way to handle pip requirements (put up as PR against counsyl/baya just for clarity and easier reviewing)

**Comment by hrichards** [comment]
More changes were needed: a later version of this PR can be found here: https://github.com/counsyl/baya/pull/21.

**Pull request closed without merging**
