### PR TITLE
Django4.1

### PR DESCRIPTION
**Pull request by kreneskyp**
## What

This PR adds support for the latest **django 4.1** and **python 3.11**

## How tested
existing unittests

### CODE REVIEW

**Comment by kreneskyp** [comment]
@jdavisp3 Is there a test pipeline for this anymore?  I can add github actions if needed.

**Comment by jdavisp3** [comment]
@kreneskyp Not that I know of.

**Comment by kreneskyp** [comment]
@jdavisp3 

Added github actions. Don't think they show up in PRs until after it's merged. Successful run here:
https://github.com/kreneskyp/baya/actions/runs/3499413263

local tests also work:
```
pkrenesky@c13589pkrenesky baya % make test

___________________________________________________________________________ summary ____________________________________________________________________________
  py37-django3.1: commands succeeded
  py37-django3.2: commands succeeded
  py38-django3.1: commands succeeded
  py38-django3.2: commands succeeded
  py38-django4.0: commands succeeded
  py38-django4.1: commands succeeded
  py39-django3.1: commands succeeded
  py39-django3.2: commands succeeded
  py39-django4.0: commands succeeded
  py39-django4.1: commands succeeded
  py310-django3.1: commands succeeded
  py310-django3.2: commands succeeded
  py310-django4.0: commands succeeded
  py310-django4.1: commands succeeded
  py311-django3.1: commands succeeded
  py311-django3.2: commands succeeded
  py311-django4.0: commands succeeded
  py311-django4.1: commands succeeded
  congratulations :)
Name                             Stmts   Miss Branch BrPart  Cover
------------------------------------------------------------------
baya/__init__.py                     8      0      0      0   100%
baya/_version.py                     1      0      0      0   100%
baya/admin/__init__.py               2      0      0      0   100%
baya/admin/options.py               40      0      2      0   100%
baya/admin/sites.py                 69      7     38     11    83%
baya/backend.py                     40      0     16      1    98%
baya/context_processors.py           9      9      4      0     0%
baya/dynamic_roles.py               21      2      2      0    91%
baya/membership.py                 102      3     16      1    97%
baya/mock_ldap_helpers.py           71      0     28      0   100%
baya/permissions.py                176      8     68      8    93%
baya/templatetags/__init__.py        0      0      0      0   100%
baya/templatetags/baya_tags.py       9      0      0      0   100%
baya/utils.py                       36      2     22      3    91%
baya/visitors.py                    65      5     14      1    92%
------------------------------------------------------------------
TOTAL                              649     36    210     25    92%
```

```
pkrenesky@c13589pkrenesky baya % make lint

flake8.checker            MainProcess    292 INFO     Checking 41 files
flake8.main.application   MainProcess   1367 INFO     Finished running
flake8.main.application   MainProcess   1367 INFO     Reporting errors
flake8.main.application   MainProcess   1368 INFO     Found a total of 44 violations and reported 0
___________________________________________________________________________ summary ____________________________________________________________________________
  lint: commands succeeded
  congratulations :)
```

**Review by jdavisp3 — APPROVED** [review]
LGTM!

**Comment by kreneskyp** [comment]
@jdavisp3 @jtratner  Do you have access to merge this?   Ilkay is working on a python 3.11 upgrade and needs these changes.

**Comment by jdavisp3** [comment]
@kreneskyp 👍

**Pull request merged**
